# imports
from pydantic import BaseModel, ConfigDict
from typing import Optional
import pandas as pd

# DatasetSummary
class DatasetSummary(BaseModel):
    row_count: int
    column_count: int                                                    # Stores the metadata extracted from the dataset.
    columns: list[str]                                                   # Used by the Planner to understand the dataset without sending the entire DataFrame to the LLM.
    data_types: dict[str, str]
    numeric_columns: list[str]
    categorical_columns:list[str]
    missing_values: dict[str, int]
    sample_data: list[dict]
    dataset_description: str

# DatasetDescription
class DatasetDescription(BaseModel):
    description: str                                                     # Structured output generated by the LLM.
                                                                         # Contains only the semantic understanding of the dataset.
# AnalysisPlan
class AnalysisTask(BaseModel):
    analysis_name: str                                                    # Represents one analysis task decided by the Planner.
    description: str                                                      # Defines what analysis to perform and what dataset columns are required.
    required_columns: list[str]

class AnalysisPlan(BaseModel):                                            # Contains the complete execution plan generated by the Planner.
    tasks: list[AnalysisTask]                                             # Acts as the contract between the Planner and the Analyzer.

class PlanReview(BaseModel):
    approved: bool
    feedback: str

# AnalysisResults
class AnalysisResult(BaseModel):                                          # Stores the output of one completed analysis.
    analysis_name: str                                                    # Keeps analysis results structured so downstream nodes can consume them reliably.
    result: dict

class AnalysisResults(BaseModel):                                         # Collects the outputs of all executed analyses.
    analyses: list[AnalysisResult]                                        # Serves as the single source of truth for the Visualizer and Insight Generator.

# BusinessInsights
class BusinessInsight(BaseModel):                                
    title: str                                                            # Represents one business insight generated from the analysis results.
    description: str                                                      # Maintains traceability by linking each insight to its source analysis.
    source_analysis: str

class BusinessInsights(BaseModel):                                        # Collects all business insights generated by the Insight Generator.
    insights: list[BusinessInsight]                                       # Used by the Insight Reviewer and Report Generator.


# GraphState
class GraphState(BaseModel):                                              # Shared state passed between all LangGraph nodes.
    user_query: str                                                       # Stores the output of each node so the workflow can evolve step by step.
    csv_path: str

    # A pandas.DataFrame is an arbitrary Python object, so Pydantic doesn't know 
    # how to validate or serialize it. Thats why we use ConfigDict
    model_config = ConfigDict(arbitrary_types_allowed=True)

    dataframe: Optional[pd.DataFrame] = None
    dataset_summary: Optional[DatasetSummary] = None
    analysis_plan: Optional[AnalysisPlan] = None
    plan_review: Optional[PlanReview] = None
    review_attempts: int = 0
    analysis_results: Optional[AnalysisResults] = None
    business_insights: Optional[BusinessInsights] = None
    chart_paths: Optional[list[str]] = None
    final_report: Optional[str] = None
    error: Optional[str] = None